name: SettlerCraft
main: com.sc.plugin.SettlerCraft
version: 0.9.8
author: Chingo247
description: Placing & building of  schematics / structures
depend: [WorldEdit, AsyncWorldEdit, WorldGuard, HolographicDisplays]
softdepend: [Vault]

commands:
    sc:
        description: SettlerCraft Commands
        usage: /sc
    cst:
        description: Construction Commands
        usage: /cst
    stt:
        description: Structure Commands
        usage: /stt

          
        
                
            

                    
                    

            
               
               