name: SettlerCraft
main: com.chingo247.settlercraft.plugin.SettlerCraft
version: 1.0-RC4
author: Chingo247
description: Build & Interact with Structures!
depend: [WorldEdit, AsyncWorldEdit, WorldGuard, Vault]
softdepend: [HolographicDisplays]

commands:
    sc:
        description: SettlerCraft Commands
        usage: /sc
    cst:
        description: Construction Commands
        usage: /cst
    stt:
        description: Structure Commands
        usage: /stt

          
        
                
            

                    
                    

            
               
               