name: SettlerCraft-WorldGuard
main: com.chingo247.settlercraft.worldguard.plugin.bukkit.SettlerCraftWorldGuarldPlugin
version: 2.1.0
author: Chingo247
description: WorldGuard support for SettlerCraft-StructureAPI
depend: [SettlerCraft-StructureAPI, WorldGuard]


    


          
        
                
            

                    
                    

            
               
               