name: SettlerCraft-StructureAPI
main: com.chingo247.settlercraft.structureapi.platforms.bukkit.BKStructureAPIPlugin
version: 2.0.0
author: Chingo247
description: StructureAPI for SettlerCraft
depend: [WorldEdit, AsyncWorldEdit, SettlerCraft-StructureAPI]
          
        
                
            

                    
                    

            
               
               