name: SettlerCraft-BackupAPI
main: com.chingo247.backupapi.bukkit.BKBackupManagerPlugin
version: 2.2.0
author: Chingo247
description: BackupAPI for Bukkit
depend: [SettlerCraft-StructureAPI, WorldEdit]
    


          
        
                
            

                    
                    

            
               
               