name: SCPerks
main: com.sc.perks.SCPerks
version: 0.9.8
author: Chingo247
description: Add additional perks to structures
depend: [SettlerCraft]

          
        
                
            

                    
                    

            
               
               