name: SettlerCraft-StructureAPI
main: com.chingo247.settlercraft.structureapi.platforms.bukkit.BKStructureAPIPlugin
version: 1.0.0
author: Chingo247
description: StructureAPI for SettlerCraft
depend: [WorldEdit, AsyncWorldEdit, SettlerCraft-Core]

commands:
    stt:
        description: Structure Commands
        usage: /stt
    


          
        
                
            

                    
                    

            
               
               