name: SettlerCraft-HolographicDisplays
main: com.chingo247.settlercraft.holographicdisplays.bukkit.plugin.SettlerCraftHolographicDisplaysPlugin
version: 2.0.0
author: Chingo247
description: HolographicDisplays support for SettlerCraft-StructureAPI
depend: [SettlerCraft-StructureAPI, HolographicDisplays]


    


          
        
                
            

                    
                    

            
               
               