name: SCStructureAPI
main: com.sc.api.structure.construction.SCStructureAPI
version: 1.0
depend: [SCMenu]

commands:
    sc:
        description: Structure related commands
        usage: /sc [arg]

          
