name: SettlerCraft-Towny
main: com.chingo247.settlercraft.towny.plugin.SettlerCraftTowny
version: 2.1.0
author: Chingo247
description: Towny support for SettlerCraft
depend: [SettlerCraft-StructureAPI]
          
        
                
            

                    
                    

            
               
               