name: SettlerCraft-MenuAPI
main: com.chingo247.menuapi.platforms.bukkit.BukkitMenuAPIPlugin
version: 2.0.0
author: Chingo247
description: Library for creating menus
depend: [SettlerCraft-Core]
soft-depend: [Vault]


          
        
                
            

                    
                    

            
               
               