name: SettlerCraftTown
main: com.chingo247.settlercrafttownapi.plugin.SettlerCraftTown
version: 0.1
author: Chingo247
description: Add Town Behavior to structures
depend: [SettlerCraft, Citizens]



          
        
                
            

                    
                    

            
               
               