name: SettlerCraft-StructureAPI
main: com.chingo247.structureapi.platforms.bukkit.BKStructureAPIPlugin
version: 1.0.0
author: Chingo247
description: Plugin that enables players to build structures!
depend: [WorldEdit, SettlerCraft-Core]


          
        
                
            

                    
                    

            
               
               