name: SettlerCraft-StructureAPI
main: com.chingo247.structureapi.platform.bukkit.BKStructureAPIPlugin
version: 2.1.0
author: Chingo247
description: StructureAPI for SettlerCraft
depend: [WorldEdit, AsyncWorldEdit, SettlerCraft-Core]

commands:
    stt:
        description: Structure Commands
        usage: /stt
    


          
        
                
            

                    
                    

            
               
               